export const disciplines = [
    { id: 'matematica', label: 'Matemática' },
    { id: 'portugues', label: 'Português' },
    { id: 'historia', label: 'História' },
    { id: 'ciencias', label: 'Ciências' },
    { id: 'geografia', label: 'Geografia' },
    { id: 'artes', label: 'Artes' },
    { id: 'biologia', label: 'Biologia' },
    { id: 'fisica', label: 'Física' },
    { id: 'quimica', label: 'Química' },
    { id: 'sociologia', label: 'Sociologia' },
    { id: 'filosofia', label: 'Filosofia' },
    { id: 'ingles', label: 'Inglês' },
    { id: 'espanhol', label: 'Espanhol' },
    { id: 'outro', label: 'Outro' },
]

export const grade = [
    { id: '1ef', label: '1º Ano - Ens. Fundamental' },
    { id: '2ef', label: '2º Ano - Ens. Fundamental' },
    { id: '3ef', label: '3º Ano - Ens. Fundamental' },
    { id: '4ef', label: '4º Ano - Ens. Fundamental' },
    { id: '5ef', label: '5º Ano - Ens. Fundamental' },
    { id: '6ef', label: '6º Ano - Ens. Fundamental' },
    { id: '7ef', label: '7º Ano - Ens. Fundamental' },
    { id: '8ef', label: '8º Ano - Ens. Fundamental' },
    { id: '9ef', label: '9º Ano - Ens. Fundamental' },
    { id: 'em', label: '1º ano – Ens. Médio' },
    { id: '2em', label: '2º ano – Ens. Médio' },
    { id: '3em', label: '3º ano – Ens. Médio' },
    { id: 'es', label: 'Ensino Superior' },
    { id: 'outro', label: 'Outro' },
]